spring.application.name=dynamicqr-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_dynamicqr
spring.datasource.username=postgres
spring.datasource.password=071100

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=dynamicqr
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.jwt.secret=${JWT_SECRET:dynamicqr-backend-jwt-secret-key-32b}
app.jwt.expiration-ms=3600000
